name: OurNet::BBS
version: 1.65
abstract: Component Object Model for BBS systems
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
build_requires:
  Test::More: 0.31
requires:
  Date::Parse: 2.20
  Date::Format: 0.01
  Digest::MD5: 2.10
  File::Temp: 0.12
  Mail::Address: 1.17
  Test::Harness: 1.23
  File::Spec: 0.6
  Hook::LexWrap: 0.01
  enum: 1.016
  if: 0.001
recommends:
  Storable: 1.011
  Net::Daemon: 0.13
  RPC::PlServer: 0.2013
  Storable: 1.011
  RPC::PlClient: 0.2013
  Class::MethodMaker: 1.00
  GnuPG::Interface: 0.31
  Term::ReadKey: 2.13
  Net::NNTP: 2.19
  Mail::Internet: 1.0
  MIME::Tools: 5.0
  IO::Scalar: 1.0
  Mail::Box: 1.0
  Net::Telnet: 3.02
  OurNet::BBSAgent: 1.55
private:
  directory:
    - inc
generated_by: Module::Install version 0.19_99
